2021-12-17 22:44:42,139 ERROR: Exception on /login [POST] [in C:\Users\toshb\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py:1777]
Traceback (most recent call last):
  File "C:\Users\toshb\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\toshb\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\toshb\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\toshb\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "C:\Users\toshb\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\toshb\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "Z:\flask\microblog\app\routes.py", line 130, in login
    if user is None or not user.check_password(form.password.data):
  File "Z:\flask\microblog\app\models.py", line 55, in check_password
    return check_password_hash(self.password_hash, password)
  File "C:\Users\toshb\AppData\Local\Programs\Python\Python39\lib\site-packages\werkzeug\security.py", line 218, in check_password_hash
    if pwhash.count("$") < 2:
AttributeError: 'NoneType' object has no attribute 'count'
2021-12-17 22:44:45,278 ERROR: Exception on /login [POST] [in C:\Users\toshb\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py:1777]
Traceback (most recent call last):
  File "C:\Users\toshb\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\toshb\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\toshb\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\toshb\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "C:\Users\toshb\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\toshb\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "Z:\flask\microblog\app\routes.py", line 130, in login
    if user is None or not user.check_password(form.password.data):
  File "Z:\flask\microblog\app\models.py", line 55, in check_password
    return check_password_hash(self.password_hash, password)
  File "C:\Users\toshb\AppData\Local\Programs\Python\Python39\lib\site-packages\werkzeug\security.py", line 218, in check_password_hash
    if pwhash.count("$") < 2:
AttributeError: 'NoneType' object has no attribute 'count'
2021-12-17 22:44:46,364 ERROR: Exception on /login [POST] [in C:\Users\toshb\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py:1777]
Traceback (most recent call last):
  File "C:\Users\toshb\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\toshb\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\toshb\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\toshb\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "C:\Users\toshb\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\toshb\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "Z:\flask\microblog\app\routes.py", line 130, in login
    if user is None or not user.check_password(form.password.data):
  File "Z:\flask\microblog\app\models.py", line 55, in check_password
    return check_password_hash(self.password_hash, password)
  File "C:\Users\toshb\AppData\Local\Programs\Python\Python39\lib\site-packages\werkzeug\security.py", line 218, in check_password_hash
    if pwhash.count("$") < 2:
AttributeError: 'NoneType' object has no attribute 'count'
